spring:
  application:
    name: crawler-service

  main:
    banner-mode: off

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: crawler-service
      auto-offset-reset: earliest

logging:
  level:
    org.apache.kafka: WARN
    org.springframework.kafka: WARN

crawl:
  executor:
    max-concurrent-batches: 1
    default-worker-job-limit: 1
    scheduler-interval: 5s
