name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-crawler-service-build:
    name: Build - services:crawler-service
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build
        run: ./gradlew :services:crawler-service:assemble --stacktrace

  backend-retailer-service-build:
    name: Build - services:retailer-service
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build
        run: ./gradlew :services:retailer-service:assemble --stacktrace


  backend-crawler-service-test:
    name: Test - services:crawler-service
    runs-on: ubuntu-latest
    needs: backend-crawler-service-build
    permissions:
      checks: write
      contents: read

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Test
        run: ./gradlew :services:crawler-service:test --stacktrace

      - name: Publish test report
        uses: mikepenz/action-junit-report@v6
        if: always()
        with:
          report_paths: backend/**/build/test-results/test/TEST-*.xml

  backend-retailer-service-test:
    name: Test - services:retailer-service
    runs-on: ubuntu-latest
    needs: backend-retailer-service-build
    permissions:
      checks: write
      contents: read

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Test
        run: ./gradlew :services:retailer-service:test --stacktrace

      - name: Publish test report
        uses: mikepenz/action-junit-report@v6
        if: always()
        with:
          report_paths: backend/**/build/test-results/test/TEST-*.xml